"""Transaction-coupled audit writing."""

import json
import math
import re
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, field_validator
from sqlalchemy.orm import Session

from pcbknowledge.platform.audit.models import AuditEvent, AuditOutcome
from pcbknowledge.platform.identity.types import Principal
from pcbknowledge.platform.ids import UUID7


class AuditTransactionRequiredError(RuntimeError):
    """Audit writes must join a caller-owned business transaction."""


class AuditEventDraft(BaseModel):
    """Validated append input; event ID and time are generated by trusted code/DB."""

    model_config = ConfigDict(frozen=True)

    organization_id: UUID7
    project_id: UUID7 | None = None
    action: str = Field(min_length=1, max_length=128, pattern=r"^[a-z0-9_.:-]+$")
    resource_type: str = Field(min_length=1, max_length=128, pattern=r"^[a-z0-9_.:-]+$")
    resource_id: UUID7 | None = None
    outcome: AuditOutcome
    request_id: str | None = Field(default=None, min_length=1, max_length=128)
    detail: dict[str, Any] = Field(default_factory=dict)

    @field_validator("detail")
    @classmethod
    def require_bounded_safe_metadata(cls, value: dict[str, Any]) -> dict[str, Any]:
        _validate_audit_value(value, depth=0, item_budget=[0])
        try:
            encoded = json.dumps(
                value,
                ensure_ascii=False,
                sort_keys=True,
                separators=(",", ":"),
            ).encode("utf-8")
        except (TypeError, ValueError) as exc:
            raise ValueError("audit detail must be canonical JSON metadata") from exc
        if len(encoded) > 4096:
            raise ValueError("audit detail exceeds 4096 encoded bytes")
        return value


class AuditWriter:
    """Flush an audit row inside the same transaction as its business mutation."""

    def append(
        self,
        session: Session,
        draft: AuditEventDraft,
        *,
        principal: Principal | None,
    ) -> AuditEvent:
        if not session.in_transaction():
            raise AuditTransactionRequiredError(
                "audit append requires an active caller-owned transaction"
            )
        # Pydantic's frozen model does not recursively freeze a nested dict.
        # Re-parse a dumped copy at the write boundary so post-validation
        # mutation cannot bypass size, depth, or sensitive-key rules.
        safe_draft = AuditEventDraft.model_validate(draft.model_dump(mode="python"))
        if principal is not None and principal.organization_id != safe_draft.organization_id:
            raise ValueError("audit principal belongs to another organization")

        event = AuditEvent(
            organization_id=safe_draft.organization_id,
            project_id=safe_draft.project_id,
            actor_subject_id=principal.subject_id if principal is not None else None,
            actor_kind=principal.kind if principal is not None else None,
            action=safe_draft.action,
            resource_type=safe_draft.resource_type,
            resource_id=safe_draft.resource_id,
            outcome=safe_draft.outcome,
            request_id=safe_draft.request_id,
            detail=safe_draft.detail,
        )
        session.add(event)
        session.flush((event,))
        return event


_SENSITIVE_AUDIT_KEYS = frozenset(
    {
        "authorization",
        "content",
        "cookie",
        "document_bytes",
        "full_text",
        "password",
        "payload",
        "raw",
        "raw_text",
        "secret",
        "source_text",
        "token",
    }
)

_SENSITIVE_AUDIT_KEY_PARTS = frozenset(
    {
        "authorization",
        "bytes",
        "content",
        "cookie",
        "credential",
        "password",
        "payload",
        "raw",
        "secret",
        "token",
    }
)


def _canonical_audit_key(value: str) -> str:
    camel_separated = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", value)
    return re.sub(r"[^a-z0-9]+", "_", camel_separated.casefold()).strip("_")


def _validate_audit_value(value: Any, *, depth: int, item_budget: list[int]) -> None:
    if depth > 3:
        raise ValueError("audit detail nesting exceeds three levels")
    if value is None or isinstance(value, bool | int):
        return
    if isinstance(value, float):
        if not math.isfinite(value):
            raise ValueError("audit detail numbers must be finite")
        return
    if isinstance(value, str):
        if len(value) > 512:
            raise ValueError("audit detail strings must not exceed 512 characters")
        return
    if isinstance(value, list):
        item_budget[0] += len(value)
        if item_budget[0] > 32:
            raise ValueError("audit detail exceeds 32 aggregate items")
        for item in value:
            _validate_audit_value(item, depth=depth + 1, item_budget=item_budget)
        return
    if isinstance(value, dict):
        item_budget[0] += len(value)
        if item_budget[0] > 32:
            raise ValueError("audit detail exceeds 32 aggregate items")
        for key, item in value.items():
            if not isinstance(key, str) or not key or len(key) > 64:
                raise ValueError("audit detail keys must be short non-empty strings")
            normalized_key = _canonical_audit_key(key)
            key_parts = frozenset(normalized_key.split("_"))
            if (
                normalized_key in _SENSITIVE_AUDIT_KEYS
                or key_parts.intersection(_SENSITIVE_AUDIT_KEY_PARTS)
                or normalized_key.endswith(("_password", "_secret", "_token"))
                or normalized_key.startswith("raw_")
                or {"source", "text"} <= key_parts
                or {"full", "text"} <= key_parts
            ):
                raise ValueError("audit detail contains a prohibited sensitive key")
            _validate_audit_value(item, depth=depth + 1, item_budget=item_budget)
        return
    raise ValueError("audit detail values must be JSON metadata")
